networks:
  back: {}
  front: {}
services:
  mariadb:
    container_name: wordpress_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root-password
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-user-password
      MYSQL_DATABASE: wordpress
    image: mariadb:latest
    networks:
      back: null
    ports:
    - 3306:3306
    restart: always
    volumes:
    - ./data:/var/lib/mysql:rw
  nginx:
    container_name: wordpress_nginx
    image: nginx:latest
    networks:
      front: null
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d:rw
    - ./nginx/log:/var/log/nginx:rw
    - ./html:/var/www/html:rw
  wordpress:
    container_name: wordpress_php
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: mysql-user
      WORDPRESS_DB_PASSWORD: mysql-user-password
    image: wordpress:4.9.4-php7.2-fpm
    networks:
      back: null
      front: null
    restart: always
    volumes:
    - ./html:/var/www/html:rw
  phpmyadmin:
    container_name: wordpress_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    networks:
      back: null
      front: null
    ports:
    - 9000:80
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root-password
      PMA_HOST: mariadb
      PMA_PORT: 3306
version: '2.0'
volumes: {}
